### ISSUE TITLE
is it possible to run this in macos?

### ISSUE THREAD

**Issue by lautrip** [vladkorotnev/traktor-obs-relay#3]
Hello, is it possible to run this in macos?

**Comment by vladkorotnev** [comment]
It should work just fine on MacOS as far as I know! 

You would need to build it manually by installing the Rust toolchain, then checkout the repository and run `cargo build --release`, then move the binary it produces back into project root and just double-click that, and that's it.

The Traktor API should also work I suppose.

Sadly I don't have any Mac on me to provide a build or test it myself :/

**Comment by lautrip** [comment]
Hi, thanks for the help.

I'm getting this error:

`Last login: Thu Jan  6 14:48:08 on ttys000
/Users/ltr/Downloads/traktor-obs-relay-master/traktor-obs-relay ; exit;
ltrs-MacBook-Pro:~ ltr$ /Users/ltr/Downloads/traktor-obs-relay-master/traktor-obs-relay ; exit;
thread 'main' panicked at 'Configuration failure: configuration file "config.toml" not found', src/settings.rs:42:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
logout
Saving session...completed.

[Process completed]
`

**Comment by lautrip** [comment]
Ok I copied the config file into my usr folder and now it worked!

**Comment by lautrip** [comment]
This is amazing, I see so much potential with this, to finally be able to have some kind of traktor live video mixing, I love it.

Maybe even some real time generated content.

**Comment by vladkorotnev** [comment]
Oh, so Mac doesn’t set working directory when launching by double clicking. Rather than copying the config it would be cleaner to use terminal from the project folder to launch it I guess. 

Glad you got it working! If you make anything feel free to submit the link into the set showcase: https://github.com/vladkorotnev/traktor-obs-relay/wiki/Set-Showcase

And if you can, please make your own design rather than using the supplied widgets, because it’s boring when everyone has the same design :-)
