### ISSUE TITLE
Various mix detection (Filter, Eq, Fader)

### ISSUE THREAD

**Issue by arnaudgst** [vladkorotnev/traktor-obs-relay#7]
Hello,

Is it possible to put the next track "ONAIR" not when the previous track has the fader at 0...
For example, is it possible to detect different position of the fader (under 50%) ?
Is it possible to do the same with the Filter Button ?

Thanks

**Comment by vladkorotnev** [comment]
Looking at the logic for on-air detection, it's just using the channel status (same as the On Air light on the mixer board): https://github.com/vladkorotnev/traktor-obs-relay/blob/master/src/logic.rs#L10

I've tried to come up with something but it seems that fader and filter are not exposed from the API side.
Looking at their code (https://github.com/ErikMinekus/traktor-api-client/blob/main/D2/Api/ApiChannel.qml) it might be possible to expose the fader status, I don't have access to my rig for the time being due to what's going on in the world so I can't really work on it, but it might be possible.
Regarding filter status I haven't found anything but then again it might be better to ask the author of the api client.

The customization of the on-air status detection would also be a good question (maybe sometime later when making a good GUI to make the whole thing more easy to use?)

**Comment by vladkorotnev** [comment]
Close for the time being as it's a bit beyond the scope of the project as it is
